trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0 
  displayName: 'Use python'

- script: pip install -r requirements.txxt
  displayName: 'Install dependencies'

- script: python index.py
  displayName: 'Run script'
