trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0 
  displayName: 'Use python'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: gem install cfn-nag
  displayName: 'Install cfn_nag'

- script: cfn_nag_scan --input-path templates 
  displayName: 'Run cfn_nag on the templates'

- script: |
    shopt -s globstar
    cfn-lint -t $(Build.SourcesDirectory)/templates/*.yaml
  displayName: 'Run cfn-lint check'
