trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0 
  displayName: 'Use python'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: gem install cfn-nag
  displayName: 'Install cfn_nag'

- script: cfn_nag_scan --input-path $(Build.SourcesDirectory)/templates 
  displayName: 'Run cfn_nag on the templates'

- task: Bash@3
  displayName: 'Run cfn-lint check'
  inputs:
    filePath: $(Build.SourcesDirectory)/cfn-lint.sh

- script: python manifest.py
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Run deployment'